export const IMAGES_URL = {
  LOGO: "/images/logo.svg",
  LOGO_WHITE: "/images/logow.svg",
  LOGIN_BACKGROUND: "/images/login_bg.jpg",
  EMAILCNEW_BACKGROUND: "/images/emailcmodel.jpg",
  EMAILC_BACKGROUND: "/images/emailBac.jpg",
  Assesment_img: "/images/skin-assesment.jpg",
  REG_BACKGROUND: "/images/regmodel.jpg",
  NOT_IMG: "/images/icon_100.png",
  LOCATION_IMG: "/images/location.png",
  GLOW_ICON1: "/images/glow_icon1.png",
  GLOW_ICON2: "/images/glow_icon2.png",
  GLOW_ICON3: "/images/glow_icon3.png",
  DOC_IMG: "/images/IMG_20201117_233830.jpg",
  GLOW_ICON4: "/images/glow_icon4.png",
  SOCIAL_ICON_FB: "/images/fb.png",
  SOCIAL_ICON_TW: "/images/twitter.png",
  SOCIAL_ICON_IN: "/images/insta.png",
  PLATINUM_CARD: "/images/platinum_card.png",
  DELUXE_CARD: "/images/deluxe_card.png",
  SIGNATURE_CARD: "/images/signature_card.png",
  GIFT_CARD_HEAD_IMG: "/images/img-10-large@2x.png",
  GLOW_TABLE: "/images/glow-table.png",
  GLOW_ICO1: "/images/glow_ico1.png",
  GLOW_ICO2: "/images/glow_ico2.png",
  GLOW_ICO3: "/images/glow_ico3.png",
  GLOW_ICO4: "/images/glow_ico4.png",
  GLOW_ICO5: "/images/glow_ico5.png",
  DUMMY: "/images/download.jpg",
  PRODUCT: "/images/new_product.jpg",
  HQ: "/images/HQ.png",
  INCREASE: "/images/vaicon1.png",
  RELOADED: "/images/vaicon2.png",
  TIME: "/images/vaicon3.png",
  C_IMG: "/images/c_img.png",
  REWARD: "/images/rewards.svg",
  PARTNERS: "/images/partners.png",
  PARTNER1: "/images/partner1.png",
  PARTNER2: "/images/partner2.png",
  PARTNER3: "/images/partner3.png",
  PARTNER4: "/images/partner4.png",
  PARTNER5: "/images/partner5.png",
  PARTNER6: "/images/partner6.png",
  TRAINING: "/images/training.png",

  REICO1: "/images/reicon1.png",
  REICO2: "/images/reicon2.png",
  REICO3: "/images/reicon3.png",
  REICO4: "/images/reicon4.png",

  TSHIRT: "/images/t-shirt.png",
  FILE: "/images/file.jpg",
  VIDEO: "/images/Hydrafacial.mp4",
  HYDRA: "/images/hydra.png",
  EVENT: "/images/event.png",

  PIC1: "/images/pic1.jpeg",
  PIC2: "/images/pic2.jpeg",
  PIC3: "/images/pic3.jpeg",
  PIC4: "/images/pic4.jpeg",
  PIC5: "/images/pic5.jpeg",
  PIC6: "/images/pic6.jpeg",
  PIC7: "/images/pics1.png",
  PIC8: "/images/pics2.png",
  PIC9: "/images/pics3.png",
  PIC10: "/images/pics4.png",
  PIC11: "/images/pics5.png",
  User: "/images/user_logo.png",

  ROUND: "/images/round.PNG",

  DASHBG1_BACKGROUND: "/images/red_bg.jpg",
  DASHBG2_BACKGROUND: "/images/blue_bg.jpg",

  RANKICO1: "/images/rank_icon1.png",
  RANKICO2: "/images/rank_icon2.png",
  RANKICO3: "/images/rank_icon3.png",
  RANKICO4: "/images/rank_icon4.png",
};
